resolver: lts-20.26
compiler: ghc-9.2.8
# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor

packages:
- .

nix:
  enable:  true
  packages: [zlib.dev, zlib.out, pkg-config, icu]

extra-deps:
- Agda-2.6.4

flags:
  Agda:
    # optimise-heavily: true
    enable-cluster-counting: true
